### ISSUE TITLE
bücher.de [DE]

### ISSUE THREAD

**Issue by gernd** [lucasfsousa/pricetag#23]
Add a scraper for buecher.de

**Comment by gernd** [comment]
I could do this @lucasfsousa ? (as I currently need it ;-) )

**Comment by lucasfsousa** [comment]
Just do it! :)

**Comment by gernd** [comment]
@lucasfsousa I have a question about the getBrand method:
For a book, this might not make sense. In this case, also no publisher is given.
Should we make getBrand return an Optional?

**Comment by lucasfsousa** [comment]
Good question, another alternative is to add brand in the metadata, but is a field that is common for most part of the scenarios. What do you think?

**Comment by gernd** [comment]
Hmm if we expect brand to be an attribute that will be present for most of the scenarios, I would rather not put into the metadata but make it Optional. I think of metada as key-value pairs that wildly differ foreach product

**Comment by lucasfsousa** [comment]
Ok, please create a new ticket for Optional on Brand. :)

**Comment by gernd** [comment]
Created new issue: https://github.com/lucasfsousa/pricetag/issues/24

**Comment by lucasfsousa** [comment]
PR: #25

**Comment by lucasfsousa** [comment]
Thanks for supporting, it will be released in 0.0.3 version.
